# Generated by Django 4.2.7 on 2023-11-26 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "git_rev",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator("^[a-f0-9]{40}$")
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("-added",),
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (0, "Unset"),
                            (1, "Negligible"),
                            (2, "Minor"),
                            (3, "Major"),
                            (4, "Huge"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Triaged"),
                            (2, "Resolved"),
                            (3, "Obsolete"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("osv", models.JSONField(blank=True, null=True)),
                (
                    "canonical",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frontend.vulnerability",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen",),
            },
        ),
        migrations.CreateModel(
            name="VulnerablePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Triaged"),
                            (2, "Resolved"),
                            (3, "Obsolete"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="frontend.evaluation",
                    ),
                ),
                (
                    "vulnerabilities",
                    models.ManyToManyField(
                        related_name="packages", to="frontend.vulnerability"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalVulnerablePackage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Triaged"),
                            (2, "Resolved"),
                            (3, "Obsolete"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vulnerable package",
                "verbose_name_plural": "historical vulnerable packages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVulnerability",
            fields=[
                ("id", models.CharField(db_index=True, max_length=128)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (0, "Unset"),
                            (1, "Negligible"),
                            (2, "Minor"),
                            (3, "Major"),
                            (4, "Huge"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Triaged"),
                            (2, "Resolved"),
                            (3, "Obsolete"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "canonical",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="frontend.vulnerability",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vulnerability",
                "verbose_name_plural": "historical vulnerabilitys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
