name: Build Nix Flake

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  build-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v15

      - run: nix build
